# Site settings
title: Rich Ramsland
email: RRamsland@gmail.com
description: Rich is a front-end developer from New York
url: http://rramsland.github.io
github_username: rramsland

# Build settings
markdown: kramdown
permalink: pretty
