# Site settings
title:Rich's Website
email:RRamsland@gmail.com
description:Rich is a front-end developer from New York
url:rramsland.github.io
github_username:rramsland

# Build settings
markdown: kramdown
permalink: pretty
